apiVersion: v1
kind: Pod
metadata:
  name: sample2
spec:
  containers:
    - name: nginx
      image: nginx
---
## Multi container
apiVersion: v1
kind: Pod
metadata:
  name: sample3
spec:
  containers:
    - name: nginx
      image: nginx
    - name: nging16
      image: nginx:1.16
 