apiVersion: v1
kind: Pod
metadata:
  name: sample7
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /opt
      name: hostpath-volume
  volumes:
  - name: hostpath-volume
    hostPath:
      # directory location on host
      path: /opt/opt-data
      # this field is optional
      type: Directory
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ebs1
spec:
  storageClassName: aws-gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
