apiVersion: v1
kind: Pod
metadata:
  name: sample9
spec:
  containers:
  - image: nginx
    name: nginx
    env:
      - name: URL
        value: google.com
      - name: URL2
        valueFrom:
          secretKeyRef:
            name: sample-secret
            key: URL2
    envFrom:
      - configMapRef:
          name: sample-data
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-data
data:
  URL1: example.com
---
apiVersion: v1
kind: Secret
metadata:
  name: sample-secret
data:
  URL2: ZXhhbXBsZS5jb20K



