apiVersion: v1
kind: Pod
metadata:
  name: sample9
spec:
  containers:
  - image: nginx
    name: nginx
    env:
      - name: URL
        value: google.com
    envFrom:
      - configMapRef:
          name: sample-data
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-data
data:
  URL1: example.com



