apiVersion: v1
kind: Pod
metadata:
  name: sample12
spec:
  containers:
  - name: nginx
    image: nginx
    livenessProbe:
      httpGet:
          path: /
      initialDelaySeconds: 5
      periodSeconds: 5

